### ISSUE TITLE
How to build project & precomplied relase

### ISSUE THREAD

**Issue by jkroepke** [Griesbacher/check_prometheus#1]
Hi,

i'm just a ops guy which doesn't have the knowledge about go. Do you can documentate, how to build this project? 

And if so, it possible to add precompiled binaries for coming releases?

**Comment by zicklam** [comment]
Hey Jan,

do you have golang/go installed on your system?

On Linux you can download and compile it with following command:

`go get github.com/griesbacher/check_prometheus`

This will build into $GOPATH/bin/check_prometheus

Have fun 👍

**Comment by jkroepke** [comment]
Long time ago ... in mean time I learned to use go build ...
